import { $Enums } from "@prisma/client";

const MeasurementUnitAbbreviation: Record<$Enums.unitOfMeasure, string> = {
    [$Enums.unitOfMeasure.bag]: 'BG',
    [$Enums.unitOfMeasure.barrel]: 'BA',
    [$Enums.unitOfMeasure.box]: 'BOX',
    [$Enums.unitOfMeasure.bunch]: 'BH',
    [$Enums.unitOfMeasure.bundle]: 'BD',
    [$Enums.unitOfMeasure.butt]: 'BU',
    [$Enums.unitOfMeasure.canister]: 'CI',
    [$Enums.unitOfMeasure.carton]: 'CT',
    [$Enums.unitOfMeasure.case]: 'CS',
    [$Enums.unitOfMeasure.container]: 'CON',
    [$Enums.unitOfMeasure.crate]: 'CR',
    [$Enums.unitOfMeasure.cubicCentimeter]: 'CU_CM',
    [$Enums.unitOfMeasure.cubicFoot]: 'CU_FT',
    [$Enums.unitOfMeasure.cubicInch]: 'CU_IN',
    [$Enums.unitOfMeasure.cubicMeter]: 'CU_M',
    [$Enums.unitOfMeasure.cubicYard]: 'CU_YD',
    [$Enums.unitOfMeasure.cup]: 'CUP',
    [$Enums.unitOfMeasure.dozen]: 'DOZ',
    [$Enums.unitOfMeasure.each]: 'EA',
    [$Enums.unitOfMeasure.canadianEach]: 'NMB',
    [$Enums.unitOfMeasure.gallon]: 'GAL',
    [$Enums.unitOfMeasure.gram]: 'G',
    [$Enums.unitOfMeasure.gross]: 'GRS',
    [$Enums.unitOfMeasure.kilogram]: 'KG',
    [$Enums.unitOfMeasure.liter]: 'L',
    [$Enums.unitOfMeasure.metricTon]: 'MT',
    [$Enums.unitOfMeasure.milliliter]: 'ML',
    [$Enums.unitOfMeasure.ounce]: 'OZ',
    [$Enums.unitOfMeasure.pair]: 'PR',
    [$Enums.unitOfMeasure.piece]: 'PC',
    [$Enums.unitOfMeasure.pint]: 'PT',
    [$Enums.unitOfMeasure.pound]: 'LB',
    [$Enums.unitOfMeasure.quart]: 'QT',
    [$Enums.unitOfMeasure.set]: 'SET',
    [$Enums.unitOfMeasure.ton]: 'T'
}