import { $Enums } from "@prisma/client";

const MeasurementUnitAbbreviation: Record<$Enums.unitOfMeasure, string> = {
    [$Enums.unitOfMeasure.bag]: 'bag',
    [$Enums.unitOfMeasure.barrel]: 'barrel',
    [$Enums.unitOfMeasure.box]: 'box',
    [$Enums.unitOfMeasure.bunch]: 'bunch',
    [$Enums.unitOfMeasure.bundle]: 'bundle',
    [$Enums.unitOfMeasure.butt]: 'butt',
    [$Enums.unitOfMeasure.canister]: 'canister',
    [$Enums.unitOfMeasure.carton]: 'carton',
    [$Enums.unitOfMeasure.case]: 'case',
    [$Enums.unitOfMeasure.container]: 'container',
    [$Enums.unitOfMeasure.crate]: 'crate',
    [$Enums.unitOfMeasure.cubicCentimeter]: 'cm³',
    [$Enums.unitOfMeasure.cubicFoot]: 'ft³',
    [$Enums.unitOfMeasure.cubicInch]: 'in³',
    [$Enums.unitOfMeasure.cubicMeter]: 'm³',
    [$Enums.unitOfMeasure.cubicYard]: 'yd³',
    [$Enums.unitOfMeasure.cup]: 'cup',
    [$Enums.unitOfMeasure.dozen]: 'dozen',
    [$Enums.unitOfMeasure.each]: 'each',
    [$Enums.unitOfMeasure.gallon]: 'gal',
    [$Enums.unitOfMeasure.gram]: 'g',
    [$Enums.unitOfMeasure.gross]: 'gross',
    [$Enums.unitOfMeasure.kilogram]: 'kg',
    [$Enums.unitOfMeasure.liter]: 'ltr',
    [$Enums.unitOfMeasure.metricTon]: 'metric ton',
    [$Enums.unitOfMeasure.milliliter]: 'ml',
    [$Enums.unitOfMeasure.ounce]: 'oz',
    [$Enums.unitOfMeasure.pair]: 'pair',
    [$Enums.unitOfMeasure.piece]: 'piece',
    [$Enums.unitOfMeasure.pint]: 'pint',
    [$Enums.unitOfMeasure.pound]: 'lb',
    [$Enums.unitOfMeasure.quart]: 'quart',
    [$Enums.unitOfMeasure.set]: 'set',
    [$Enums.unitOfMeasure.ton]: 'ton',
    [$Enums.unitOfMeasure.tray]: 'tray'
}